name: Deploy

on:
  push:
    branches:
      - main  # Se ejecutará cuando hagas push en la rama `main`

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup environment variables
        run: echo "MYSQL_CONNECTION_STRING=${{ secrets.MYSQL_CONNECTION_STRING }}" >> $GITHUB_ENV

      - name: Verificar variable (solo para pruebas, quítalo después)
        run: echo $MYSQL_CONNECTION_STRING
