name: Deploy  # Nombre del workflow

on:
  push:
    branches:
      - main  # Se ejecutará cuando hagas push en la rama `main`

jobs:
  deploy:
    runs-on: ubuntu-latest  # Usamos un runner de Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Clona el código del repositorio

      - name: Setup environment variables
        run: echo "MYSQL_CONNECTION_STRING=${{ secrets.MYSQL_CONNECTION_STRING }}" >> $GITHUB_ENV

      - name: Verificar variable (solo para pruebas, quítalo después)
        run: |
          echo "Longitud de MYSQL_CONNECTION_STRING: ${#MYSQL_CONNECTION_STRING}"
